spring:
    application:
        name: spring-boot-postgres-replica-connection-demo
    datasource:
        jdbc-url: jdbc:postgresql://localhost:5432/info
        password: postgres
        username: postgres
        hikari:
            connectionTimeout: 30000
            idleTimeout: 600000
            maxLifetime: 1800000
        replica:
            jdbc-url: jdbc:postgresql://localhost:25432/info
            password: postgres
            username: postgres
            hikari:
                connectionTimeout: 30000
                idleTimeout: 600000
                maxLifetime: 1800000
    flyway:
        enabled: false
        url: jdbc:postgresql://localhost:5432/info
        user: postgres
        password: postgres
        locations: classpath:/db/migration
        baseline-on-migrate: true
        baseline-version: 1.1
        out-of-order: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                connection:
                    handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
                dialect: org.hibernate.dialect.PostgreSQLDialect
